name: dados_economicos
version: '1.0'
config-version: 2

profile: dados-economicos

model-paths: ["models/staging", "models/intermediate", "models/marts"]
analysis-paths: ["models/analysis"]
test-paths: ["models/tests"]
seed-paths: ["models/data"]
snapshot-paths: ["models/snapshots"]

target-path: target
clean-targets:
  - target
  - dbt_modules


