name: dados_economicos
version: '1.0'
config-version: 2

profile: dados-economicos

model-paths: ["warehouse/models/staging", "warehouse/models/intermediate", "warehouse/models/marts"]
analysis-paths: ["warehouse/models/analysis"]
test-paths: ["warehouse/models/tests"]
seed-paths: ["warehouse/models/data"]
snapshot-paths: ["warehouse/models/snapshots"]

target-path: target
clean-targets:
  - target
  - dbt_modules


