# Usa a imagem base do Python
FROM python:3.8-slim

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos do projeto para o diretório de trabalho no contêiner
COPY . /app/

# Copia a pasta .streamlit para o diretório de trabalho no contêiner
COPY .streamlit /app/.streamlit

# Atualiza o pip
RUN pip install --upgrade pip

# Limpa o cache do pip
RUN pip cache purge

# Instala as dependências do projeto
RUN pip install --no-cache-dir \
    plotly==5.22.0 \
    pandas \
    pymssql==2.3.0 \
    python-dotenv==1.0.1 \
    streamlit==1.36.0 \
    st-pages==0.5.0 

# Exponha a porta que o Streamlit usará
EXPOSE 8501

# Define a variável de ambiente para o Streamlit
ENV STREAMLIT_PORT=8501

# Comando padrão a ser executado quando o contêiner for iniciado
CMD ["streamlit", "run", "main.py"]
