version: 2

sources:
  - name: raw
    description: "Dados brutos carregados por processos ETL externos"
    tables:
      - name: 1: Taxa de C창mbio D처lar
        description: "Taxa de c창mbio - Livre - D처lar Americano (venda)"

